name: HACS Validate

on:
  push:
    tags:
    - 'v*'
  schedule:
    - cron: "0 0 * * 1"

jobs:
  validate-hacs:
    if: github.repository == 'nathan-gs/ha-map-card'
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "plugin"
